spring:
  profiles:
    active: dev
    include:
      - custom
  application:
    name: cyf-erp-webboot
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  cache:
    type: ehcache
  main:
    allow-circular-references: true
  jpa:
    # MySQL配置
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    druid:
      # MySQL配置
      url: jdbc:mysql://${CYF_MYSQL_IP}:${CYF_MYSQL_PORT}/${CYF_MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false
      username: ${CYF_MYSQL_USERNAME}
      password: ${CYF_MYSQL_PASSWORD}
      max-active: 200

server:
  port: 18888
  compression:
    enabled: true
  servlet:
    context-path: /cyf/too/kit
  undertow:
    threads:
      worker: 256

springdoc:
  swagger-ui:
    doc-expansion: none

mybatis-plus:
  global-config:
    db-config:
      update-strategy: ignored